### ISSUE TITLE
TopicController 这个类有内存泄露

### ISSUE THREAD

**Issue by tailang** [swordray/ruby-china-ios#3]
发现TopicController 有内存泄露，能力有限，一直在用oc，没用swift写过东西，没法定位到是哪行代码引起的。作者可以查查看...

**Comment by swordray** [comment]
估计是每个回帖都需要单独使用 UIWebView 导致内存过高

**Comment by tailang** [comment]
我定位到导致内存泄露的问题，已提PR

**Comment by swordray** [comment]
#4
