### ISSUE TITLE
如何把这个app用于其他的使用ruby-china源代码搭建的网站

### ISSUE THREAD

**Issue by seveniruby** [swordray/ruby-china-ios#7]
没发现有什么地方可以统一的修改 ruby-china.org这个网站的指向.

**Comment by lijy91** [comment]
https://github.com/swordray/ruby-china-ios/blob/master/RubyChina/Libraries/Helper.swift

在这个文件搜索一下 baseURL 就可以看到了。

**Comment by seveniruby** [comment]
估计不行吧. 因为我看到 RubyChina/Controllers/TopicController.swift  里面也硬编码了ruby-china.org的网址. 

另外Helper.swift里面的baseUrl为什么是http://ruby-china.secipin.com 哪 , 这是出于什么样的目的啊?

**Comment by swordray** [comment]
TopicController.swift 硬编码是正常的，因为帖子内容里会写死类似 https://ruby-china.org/topics/28964 这样的地址
ruby-china.secipin.com 是 API 中转服务器，用来处理 OAuth 认证

**Comment by swordray** [comment]
已重写 2.0 版本，如有需要请与我联系。
